# Generated by Django 3.1.6 on 2021-02-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='largura',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=4),
            preserve_default=False,
        ),
    ]
