# Generated by Django 3.1.6 on 2021-02-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20210211_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cor',
            new_name='Color',
        ),
    ]
