# Generated by Django 3.1.6 on 2021-02-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20210211_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cores',
            new_name='color',
        ),
    ]
